//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tour.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Blog
    {
        public int BlogId { get; set; }
        public int UserId { get; set; }
        [Required(ErrorMessage = "Can't be empty!")]
        public string BlogTitle { get; set; }
        [Required(ErrorMessage = "Can't be empty!")]
        public string BlogBody { get; set; }
    }
}
