//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tour.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ContactU
    {
        public int ContactUsId { get; set; }
        [Required(ErrorMessage = "Can't be empty!")]
        public string Email { get; set; }
        [Required(ErrorMessage = "Can't be empty!")]
        public string Subject { get; set; }
        [Required(ErrorMessage = "Can't be empty!")]
        public string Message { get; set; }
    }
}
